<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFrameworks>net6.0;net8.0</TargetFrameworks>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <IsPackable>true</IsPackable>

    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
    <JsLibRoot>JsLib\</JsLibRoot>

    <Title>Apprentice Foundry Blazor</Title>
    <description>2D and 3D graphics for blazor applications</description>
    <packageTags>Foundry, 2D, 3D, Visio, Blazor</packageTags>
    <RepositoryUrl>hhttps://github.com/ApprenticeFoundry/FoundryBlazor</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageId>ApprenticeFoundryBlazor</PackageId>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <Copyright>Copyright © 2020</Copyright>
    <AssemblyVersion>12.8.0</AssemblyVersion>
    <Version>12.8.0</Version>
    <Authors>Stephen Strong</Authors>
    <Company>Stephen Strong</Company>
    <PackageProjectUrl>https://apprenticefoundry.github.io/</PackageProjectUrl>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <Optimize>True</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <!-- <ProjectReference Include="..\BlazorThreeJS\BlazorThreeJS.csproj" /> -->
    <PackageReference Include="ApprenticeFoundryBlazorThreeJS" Version="4.2.0" />
    <PackageReference Include="Blazor.Extensions.Canvas" Version="1.1.1" />
    <PackageReference Include="BlazorComponentBus" Version="2.2.0" />

    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="7.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Core" Version="1.1.0" />
    <PackageReference Include="QRCoder" Version="1.4.3" />
    <PackageReference Include="Radzen.Blazor" Version="4.11.2" />
    <PackageReference Include="SkiaSharp" Version="2.88.6" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="2.88.3" />
  </ItemGroup>


</Project>
